### PR TITLE
QCheck2.Gen.string_readable -> QCheck2.Gen.string_printable

### PR DESCRIPTION
**Pull request by jmid**
Following up on issue #155, this PR
- renames `QCheck2.Gen.string_readable` to `string_printable`
- updates its `char` generator to use `Gen.printable`
- updates the documentation
- updates the tests

As far as I can tell, QCheck2 hasn't been released yet, so we can do a hard renaming (and avoid a deprecation).

CC @sir4ur0n @vch9: are you OK with this change?

### CODE REVIEW

**Comment by jmid** [comment]
Ha! I (naturally) forgot to update the expected output - but the CI tests caught it. 😄

**Review by sir4ur0n — APPROVED** [review]

**Comment by sir4ur0n** [comment]
> CC @sir4ur0n: are you OK with this change?

Of course :smile: This is a good change, thank you!

**Comment by vch9** [comment]
I think the hard renaming is ok, however you could add it to the changelog.

**Comment by vch9** [comment]
> CC @vch9: are you OK with this change?
Absolutely, thank you! :smiley:

**Pull request merged**
