### PR TITLE
WIP: tech (format): Add ocamlformat and format QCheck.ml

### PR DESCRIPTION
**Pull request by Sir4ur0n**
Same as https://github.com/c-cube/qcheck/pull/128

### CODE REVIEW

**Comment by vch9** [comment]
I can give you access to #128 or close it if you'd prefer.

**Comment by c-cube** [comment]
let's close #128 . does this reformat all the files, or only one, @Sir4ur0n ? is there a `make format` command or something like that?

**Comment by Sir4ur0n** [comment]
My bad, I should have explained further 😅 The goal of this PR was to show the alternative with `exp-grouping=preserve` to see if @c-cube would agree with such a format (and I couldn't change #128 ).

@vch9 if you want to rebase and update your PR, it's definitely ok, I'll close mine.

@c-cube just like #128 this PR only reformats `QChecm.ml` for now, to see if you agree with it or not. If you do, we can easily reformat all files.

As for a `make format` command, I don't have any use for this (as I configure my editors to format on save) but I don't mind if we (here or in #128) add it either

**Comment by c-cube** [comment]
well ideally there'd be a `make format` for people who didn't configure their editor, *and* some check in the CI that code is well formatted.

**Comment by vch9** [comment]
I'll have a look at `make format`

**Comment by vch9** [comment]
> I'll have a look at `make format`

see #128

**Comment by Sir4ur0n** [comment]
Closing as this change is incorporated in #128

**Pull request closed without merging**
