### PR TITLE
warn/fail if too many preconditions failed

### PR DESCRIPTION
**Pull request by c-cube**
see #55; cc @porglezomp @Gbury 

to test: `make example-runner`, see messages at the beginning.

### CODE REVIEW

**Comment by Gbury** [comment]
The part about detection looks good, but the printing of errors is problematic.

Specifically, the errors printed heavily mess with the verbose output in the Qcheck_runner_test example. Additionally, these errors are printed out of order (all the other failures are printed in the order of tests, whereas these errors appear at the start of the output in non verbose mode).
 Instead of printing the error on stderr, wouldn't it be simpler to return a failure result (and not a success) for the test ?

**Comment by c-cube** [comment]
Not a precise idea, but probably some opaque type (a record) with a list of warnings inside and a `view` function that returns the normal sum type. Also I'd like to make the sum types use inner records so they're more future proof and readable.

**Comment by c-cube** [comment]
extended the state.

**Comment by Gbury** [comment]
Seems good overall. Could the number of warnings be printed at the end (together with the number of failed tests, errored tests, and total number of tests) ?

**Comment by c-cube** [comment]
There you go.

**Pull request merged**
