### PR TITLE
Fix `QCheck2.Gen.small_string` impl to match interface and documentation

### PR DESCRIPTION
**Pull request by jmid**
This PR updates the `QCheck2.Gen.small_string` to match the interface and documentation following my finding in #153:
```ocaml
  val small_string : ?gen:char t -> string t
  (** Builds a string generator, length is {!small_nat}.
      Accepts an optional character generator (the default is {!char}).

      Shrinks on the number of characters first, then on the characters.
  *)
```

### CODE REVIEW

**Comment by vch9** [comment]
:+1:

**Comment by jmid** [comment]
It is nice to align the `.ml` and `.mli` for consistency.
However, as far as I can tell (see examples and discussion in #162) this still means that the parameter is defacto labelled - and thus required. Merging this fix does not change that - meaning the documentation+interface should be updated 😬🤷‍♂️
As such I'm hesitant with the merge, because we will have to make some additional changes anyway...

I'd therefore like your input on the discussion in #162 @vch9 @sir4ur0n @c-cube 
(I'd also be grateful if one of you would confirm by cloning, running `dune utop` and pasting the examples)

**Review by sir4ur0n — APPROVED** [review]

**Review by sir4ur0n — APPROVED** [review]
While it doesn't solve the "optional mandatory" argument design issue you mentioned, it doesn't hurt in any way, so it's still positive :+1:

**Comment by jmid** [comment]
Closing as this is addressed in #245

**Pull request closed without merging**
