### PR TITLE
[WIP] Attemps at fixing the CI

### PR DESCRIPTION
**Pull request by vch9**

### CODE REVIEW

**Comment by jmid** [comment]
I believe the failure is due to alcotest changing its output #193
Accepting the new input would thus make the tests fail with a pre 1.5.0 alcotest instead.
I looked at the issue initially and proposed a fix in #193 to make the shell-script stable to such whitespace changes,
but then got side-tracked.

**Comment by vch9** [comment]
We could also as it was done [in mirage packages/qcheck-alcotest/qcheck-alcotest.0.18/opam](https://github.com/mirage/alcotest/pull/331) restrict alcotest versions?

**Comment by jmid** [comment]
> We could also as it was done [in mirage packages/qcheck-alcotest/qcheck-alcotest.0.18/opam](https://github.com/mirage/alcotest/pull/331) restrict alcotest versions?

Yes, that is an option.
I think it would be preferable to make our CI tests a bit more robust rather than insist on Alcotest 1.5.0 because it happens to output 1 less newline, to avoid such a small change to break it in the future. @c-cube ?

I don't find my `sed + tr` proposal particularly pretty though... 😬

**Comment by c-cube** [comment]
making the test more robust is always good, yes.

**Comment by jmid** [comment]
> making the test more robust is always good, yes.

@c-cube The alternative is now in PR #203. Can I ask you to merge one of these? It would be nice to get CI running again 🙂

**Comment by vch9** [comment]
> > making the test more robust is always good, yes.
> 
> @c-cube The alternative is now in PR #203. Can I ask you to merge one of these? It would be nice to get CI running again slightly_smiling_face

Thank you! Thereby closing this.

**Pull request closed without merging**
